// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdf7cGuhSSyhJURJuoQSNXbCDHkt74iDQ',
    appId: '1:698424572962:web:24d159684b6896a97ede7b',
    messagingSenderId: '698424572962',
    projectId: 'agentic-crisis-detection',
    authDomain: 'agentic-crisis-detection.firebaseapp.com',
    databaseURL: 'https://agentic-crisis-detection-default-rtdb.firebaseio.com',
    storageBucket: 'agentic-crisis-detection.firebasestorage.app',
    measurementId: 'G-1HQCF75WRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjLPy-PXXff5EcutaaiGPOp1_i59EaP0k',
    appId: '1:698424572962:android:9680e315e7f0ad2b7ede7b',
    messagingSenderId: '698424572962',
    projectId: 'agentic-crisis-detection',
    databaseURL: 'https://agentic-crisis-detection-default-rtdb.firebaseio.com',
    storageBucket: 'agentic-crisis-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqDxIr8a4D9z1xb_Jd-ogNeDH_oiolko',
    appId: '1:698424572962:ios:f8aabbe455883ad17ede7b',
    messagingSenderId: '698424572962',
    projectId: 'agentic-crisis-detection',
    databaseURL: 'https://agentic-crisis-detection-default-rtdb.firebaseio.com',
    storageBucket: 'agentic-crisis-detection.firebasestorage.app',
    iosBundleId: 'com.ciro.ciro',
  );
}
